import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
export default function SprintCard({ sprint, projectId, onEdit, onDelete, }) {
    const navigate = useNavigate();
    return (_jsxs("div", { className: "\r\ngroup\r\nrelative\r\noverflow-hidden\r\nbg-gray-900/70\r\nborder\r\nborder-gray-800\r\nrounded-3xl\r\np-6\r\nshadow-xl\r\nhover:border-blue-500/50\r\nhover:shadow-blue-600/20\r\nduration-300\r\n", children: [_jsx("div", { className: "\r\nabsolute\r\nw-32\r\nh-32\r\nbg-purple-600/10\r\nrounded-full\r\nblur-3xl\r\n-top-10\r\n-right-10\r\ngroup-hover:bg-purple-600/20\r\nduration-300\r\n" }), _jsx("div", { className: "\r\nrelative\r\nflex\r\njustify-between\r\nitems-start\r\ngap-5\r\n", children: _jsxs("div", { className: "\r\nflex\r\nitems-center\r\ngap-4\r\n", children: [_jsx("div", { className: "\r\nw-14\r\nh-14\r\nrounded-2xl\r\nbg-gradient-to-br\r\nfrom-blue-600\r\nto-purple-600\r\nflex\r\nitems-center\r\njustify-center\r\ntext-2xl\r\nshadow-lg\r\n", children: "\u26A1" }), _jsxs("div", { children: [_jsx("h2", { className: "\r\ntext-xl\r\nfont-black\r\nline-clamp-1\r\n", children: sprint.name }), _jsx("p", { className: "\r\ntext-green-400\r\ntext-xs\r\nmt-1\r\n", children: "\u25CF Active Sprint" })] })] }) }), _jsx("p", { className: "\r\nrelative\r\ntext-gray-400\r\nmt-6\r\nleading-relaxed\r\nline-clamp-3\r\nmin-h-4\r\n", children: sprint.goal || "No sprint goal added yet." }), _jsxs("div", { className: "\r\nrelative\r\ngrid\r\ngrid-cols-2\r\ngap-3\r\nmt-6\r\n", children: [_jsxs("div", { className: "\r\nbg-gray-800/70\r\nrounded-xl\r\np-3\r\n", children: [_jsx("p", { className: "\r\ntext-xs\r\ntext-gray-500\r\n", children: "Type" }), _jsx("p", { className: "\r\nfont-semibold\r\n", children: "Agile" })] }), _jsxs("div", { className: "\r\nbg-gray-800/70\r\nrounded-xl\r\np-3\r\n", children: [_jsx("p", { className: "\r\ntext-xs\r\ntext-gray-500\r\n", children: "Status" }), _jsx("p", { className: "\r\nfont-semibold\r\ntext-blue-400\r\n", children: "Running" })] })] }), _jsxs("div", { className: "\r\nrelative\r\ngrid\r\ngrid-cols-1\r\nsm:grid-cols-3\r\ngap-3\r\nmt-8\r\n", children: [_jsx("button", { onClick: () => {
                            console.log("OPEN PROJECT", projectId);
                            navigate(`/projects/${projectId}/sprints/${sprint._id}`);
                        }, className: "\r\npy-3\r\nrounded-xl\r\nfont-bold\r\nbg-gradient-to-r\r\nfrom-green-600\r\nto-emerald-600\r\nhover:scale-105\r\nduration-300\r\nshadow-lg\r\nshadow-green-600/20\r\n", children: "Open" }), _jsx("button", { onClick: () => onEdit(sprint), className: "\r\npy-3\r\nrounded-xl\r\nfont-bold\r\nbg-gradient-to-r\r\nfrom-blue-600\r\nto-indigo-600\r\nhover:scale-105\r\nduration-300\r\nshadow-lg\r\nshadow-blue-600/20\r\n", children: "Edit" }), _jsx("button", { onClick: () => onDelete(sprint._id), className: "\r\npy-3\r\nrounded-xl\r\nfont-bold\r\nbg-gradient-to-r\r\nfrom-red-600\r\nto-pink-600\r\nhover:scale-105\r\nduration-300\r\nshadow-lg\r\nshadow-red-600/20\r\n", children: "Delete" })] })] }));
}
