import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";
export default function Navbar() {
    const { logout, user } = useAuth();
    const nav = useNavigate();
    return (_jsxs("div", { className: "\r\nh-auto\r\nmin-h-20\r\nbg-gray-950/80\r\nbackdrop-blur-xl\r\nborder-b\r\nborder-gray-800\r\nflex\r\nflex-col\r\nsm:flex-row\r\njustify-between\r\nitems-start\r\nsm:items-center\r\ngap-5\r\npx-5\r\nsm:px-8\r\npy-4\r\ntext-white\r\nsticky\r\ntop-0\r\nz-40\r\n", children: [_jsxs("div", { children: [_jsxs("h2", { className: "\r\ntext-xl\r\nsm:text-2xl\r\nfont-black\r\n", children: ["Welcome back,", " ", _jsx("span", { className: "\r\nbg-gradient-to-r\r\nfrom-blue-400\r\nto-purple-500\r\nbg-clip-text\r\ntext-transparent\r\n", children: user?.name || "User" }), "\uD83D\uDC4B"] }), _jsx("p", { className: "\r\ntext-gray-400\r\ntext-sm\r\nmt-1\r\n", children: "Manage your projects and productivity" })] }), _jsxs("div", { className: "\r\nflex\r\nitems-center\r\ngap-4\r\nw-full\r\nsm:w-auto\r\n", children: [_jsxs("div", { className: "\r\nhidden\r\nmd:flex\r\nitems-center\r\ngap-2\r\nbg-green-500/10\r\nborder\r\nborder-green-500/30\r\ntext-green-400\r\npx-4\r\npy-2\r\nrounded-xl\r\ntext-sm\r\n", children: [_jsx("span", { className: "\r\nw-2\r\nh-2\r\nbg-green-500\r\nrounded-full\r\nanimate-pulse\r\n" }), "Online"] }), _jsxs("div", { className: "\r\nhidden\r\nsm:flex\r\nitems-center\r\ngap-3\r\nbg-gray-900\r\nborder\r\nborder-gray-800\r\npx-4\r\npy-2\r\nrounded-xl\r\n", children: [_jsx("div", { className: "\r\nw-9\r\nh-9\r\nrounded-full\r\nbg-gradient-to-r\r\nfrom-blue-600\r\nto-purple-600\r\nflex\r\nitems-center\r\njustify-center\r\nfont-bold\r\n", children: user?.name ? user.name.charAt(0).toUpperCase() : "U" }), _jsxs("div", { children: [_jsx("p", { className: "\r\ntext-sm\r\nfont-semibold\r\n", children: user?.name }), _jsx("p", { className: "\r\ntext-xs\r\ntext-gray-500\r\n", children: "Workspace" })] })] }), _jsx("button", { onClick: () => {
                            logout();
                            nav("/");
                        }, className: "\r\nml-auto\r\nsm:ml-0\r\nbg-gradient-to-r\r\nfrom-red-600\r\nto-pink-600\r\npx-5\r\npy-3\r\nrounded-xl\r\nfont-semibold\r\nhover:scale-105\r\nduration-300\r\nshadow-lg\r\nshadow-red-600/20\r\n", children: "Logout" })] })] }));
}
